"""
report_generator.py
--------------------
Builds the "AI-Generated Verification Report" as clean HTML (downloadable /
printable to PDF by the browser -- keeps us dependency-light and zero-cost;
no PDF library required).
"""

from datetime import datetime
from evidence_engine import document_verifiability_score

REPORT_CSS = """
body{font-family:'Segoe UI',Arial,sans-serif;background:#0b1220;color:#dbe6ff;padding:32px;max-width:900px;margin:auto;}
h1{color:#4fd1ff;} h2{color:#7dd3fc;border-bottom:1px solid #223354;padding-bottom:6px;margin-top:32px;}
table{width:100%;border-collapse:collapse;margin:12px 0;}
th,td{border:1px solid #223354;padding:8px 10px;text-align:left;font-size:14px;}
th{background:#101c33;color:#7dd3fc;}
.badge{padding:2px 8px;border-radius:10px;font-size:12px;font-weight:600;}
.hp{background:#3a1420;color:#ff8080;} .nv{background:#3a2f10;color:#ffd166;}
.cs{background:#0f3a24;color:#6ee7b7;} .ab{background:#241a3a;color:#c4a6ff;}
.meta{color:#8aa0c8;font-size:13px;}
"""


def _badge(verdict):
    m = {"high_priority": ("hp", "High Priority"), "needs_verification": ("nv", "Needs Verification"),
         "context_sufficient": ("cs", "Context Sufficient"), "abstain": ("ab", "AI Abstained")}
    cls, label = m.get(verdict, ("nv", verdict))
    return f'<span class="badge {cls}">{label}</span>'


def generate_report_html(analyses, source_label="Pasted text"):
    total = len(analyses)
    counts = {"context_sufficient": 0, "needs_verification": 0, "high_priority": 0, "abstain": 0}
    for a in analyses:
        counts[a["verdict"]] = counts.get(a["verdict"], 0) + 1

    doc_score, doc_band = document_verifiability_score(analyses)
    riskiest = max(analyses, key=lambda a: a["risk_score"]) if analyses else None

    rows = ""
    for a in analyses:
        rows += (f"<tr><td>{a['claim']}</td><td>{_badge(a['verdict'])}</td>"
                 f"<td>{a['claim_type_label']}</td><td>{a['risk_score']}/100 ({a['risk_band']})</td>"
                 f"<td>{a['context_sufficiency_pct']}%</td></tr>")

    recs = []
    if counts.get("high_priority", 0):
        recs.append("Verify all high-priority claims first -- they carry the greatest downstream risk.")
    if counts.get("needs_verification", 0):
        recs.append("Review claims needing verification against retrieved evidence before publishing.")
    if any(a.get("temporal_sensitive") for a in analyses):
        recs.append("Re-check time-sensitive claims closer to publication; status may have changed.")
    if counts.get("abstain", 0):
        recs.append("Route abstained claims to a human reviewer -- the system's confidence was too low to decide.")
    if not recs:
        recs.append("No claims required escalation in this pass.")

    recs_html = "".join(f"<li>{r}</li>" for r in recs)

    html = f"""<!DOCTYPE html><html><head><meta charset="utf-8">
    <title>VeriScope AI Verification Report</title><style>{REPORT_CSS}</style></head><body>
    <h1>\U0001F4C4 VeriScope AI Verification Report</h1>
    <p class="meta">Source: {source_label} &middot; Generated {datetime.now().strftime('%Y-%m-%d %H:%M UTC')}</p>

    <h2>Summary</h2>
    <p>Total Claims Analyzed: <b>{total}</b></p>
    <ul>
      <li>\U0001F7E2 Context Sufficient: {counts.get('context_sufficient',0)}</li>
      <li>\U0001F7E1 Needs Verification: {counts.get('needs_verification',0)}</li>
      <li>\U0001F534 High Priority: {counts.get('high_priority',0)}</li>
      <li>\U0001F6D1 AI Abstained: {counts.get('abstain',0)}</li>
    </ul>

    <h2>Document Verifiability Score</h2>
    <p><b>{doc_score} / 100</b> &mdash; {doc_band}<br>
    <span class="meta">This measures how much of the document can be responsibly assessed from
    available context and signals -- it is not a "truth score."</span></p>

    {"<h2>Most Risky Claim</h2><p><b>" + riskiest['claim'] + "</b><br>Risk Score: " + str(riskiest['risk_score']) + "/100 (" + riskiest['risk_band'] + ")<br>Reason: " + "; ".join(riskiest['reasons']) + "</p>" if riskiest else ""}

    <h2>All Claims</h2>
    <table><tr><th>Claim</th><th>Verdict</th><th>Type</th><th>Risk</th><th>Context Support</th></tr>
    {rows}
    </table>

    <h2>Recommended Next Actions</h2>
    <ol>{recs_html}</ol>

    <p class="meta">Generated by VeriScope AI &mdash; an NLP claim-auditing prototype built for
    Learn Depth problem ML-T2-061. This report flags claims for verification; it does not
    assert truth or falsehood.</p>
    </body></html>"""
    return html